# Generated by Django 4.2.5 on 2023-10-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tabelka', '0004_armys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armys',
        ),
    ]
